name: Project CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 브랜치 및 파일을 가져와 gradlew가 누락되지 않도록 설정

      - name: Debug workspace
        run: ls -la backend  # GitHub Actions에서 gradlew 파일이 존재하는지 확인

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Run Checkstyle (Log Only)
        run: |
          ./gradlew checkstyleMain || echo "Checkstyle warnings detected, but not failing CI"
        working-directory: backend

      - name: Build with Gradle (Skip Checkstyle)
        run: ./gradlew clean build -x test -x checkstyleMain --no-daemon
        working-directory: backend

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Project
          path: backend/build/libs/*.jar
