name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js & Enable pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Debug pnpm Installation
        run: |
          echo "Checking pnpm installation..."
          which pnpm || echo "pnpm not found"
          echo "Current PATH: $PATH"
          echo "Checking npm global bin directory..."
          npm root -g

      - name: Install pnpm (if missing)
        run: |
          if ! command -v pnpm &> /dev/null
          then
            echo "pnpm not found, installing..."
            npm install -g pnpm
            echo "export PATH=$(npm root -g)/pnpm/bin:$PATH" >> $HOME/.bashrc
            source $HOME/.bashrc
          fi
          echo "pnpm location:"
          which pnpm
          echo "Final PATH: $PATH"
          pnpm --version

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: pnpm build --mode production

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.FE_AWS_REGION }}
        run: aws s3 sync ./dist s3://studyroom-ice-webpage --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.FE_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
